# Generated by Django 2.1 on 2018-08-16 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyManagment', '0005_auto_20180816_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='company',
        ),
    ]
