# Generated by Django 2.1 on 2018-08-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyManagment', '0007_userprofile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
