# Generated by Django 2.1 on 2018-08-16 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyManagment', '0008_userprofile_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
