# Generated by Django 2.1 on 2018-08-17 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companyManagment', '0023_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='invitedby',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitedby', to=settings.AUTH_USER_MODEL),
        ),
    ]
