# Generated by Django 2.1 on 2018-08-17 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companyManagment', '0026_auto_20180817_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='invitedby',
        ),
        migrations.AddField(
            model_name='invitation',
            name='invitedby',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, related_name='invitedby', to=settings.AUTH_USER_MODEL),
        ),
    ]
