# Generated by Django 2.1 on 2018-08-17 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyManagment', '0027_auto_20180817_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='invitedby',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='user',
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
