# Generated by Django 2.1 on 2018-08-17 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyManagment', '0029_invitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
    ]
